spring:
  datasource:
    url: jdbc:mysql://129.204.36.134:3306/mydb?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456-abc
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false
