spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://129.204.36.134:3306/mydb?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456-abc
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false

#导出 excel 的配置
export:
  page-size: 600000
  sql-directory: sql
  excel-directory:

