DROP TABLE tb_test;
CREATE TABLE `tb_test` (
  `id` int(255) unsigned NOT NULL AUTO_INCREMENT,
  `clo1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo2` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo3` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo4` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo5` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo6` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo7` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo8` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo9` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo10` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo11` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo12` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo13` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo14` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo15` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo16` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo17` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo18` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo19` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo20` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo21` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo22` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo23` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo24` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo25` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo26` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo27` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo28` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo29` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clo30` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;